networks:
  proxy:
    name: system_proxy
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    labels:
        - traefik.enable=true
        - traefik.docker.network=system_proxy
        # # middleware redirection http to https
        - traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.permanent=true
        # # http with redirection to https
        - traefik.http.routers.jellyfin.entrypoints=web
        - traefik.http.routers.jellyfin.rule=Host(`jellyfin.aubinina.eu`)
        - traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect
        # https
        - traefik.http.routers.jellyfin-secure.entrypoints=websecure
        - traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.aubinina.eu`)
        - traefik.http.routers.jellyfin-secure.tls=true
        # service
        - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    # user: uid:gid
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - type: bind
        source: /d/films
        target: /media
        read_only: true
    #   - type: bind
    #     source: /path/to/media2
    #     target: /media2
    #     read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
    #   - type: bind
    #     source: /path/to/fonts
    #     target: /usr/local/share/fonts/custom
    #     read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.aubinina.eu
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 8096:8096
    networks:
      - default
      - proxy
